source 'https://rubygems.org'

gem "rake", "~> 10.0.4"
gem "require_all", "~> 1.2.1"
gem "rails", "~> 3.2.13"
gem "rspec", "~> 2.13.0"
gem "rspec", "~> 2.13.0"
gem 'mysql2'

gem "cap_git_tools", "~> 0.9.1"
gem "git", "~> 1.2.5"
gem "mail", "~> 2.5.4"
gem "rails_config", "~> 0.3.2"
gem "capistrano", "~> 2.15.5"
gem "rvm-capistrano", "~> 1.4.0"
gem "newrelic_rpm", "~> 3.6.0"
gem "rails_config", "~> 0.3.2"
